### ISSUE TITLE
Getting error in the Gapminder-App

### ISSUE THREAD

**Issue by Inkimar** [ChrisBeeley/gapminder#1]
Hi!

I am running  R 3.6.3 and rStudio.

when running the gapminder project I get the following error

```
Warning: Error in : Corrupt `grouped_df` using old (< 0.8.0) format.
ℹ Strip off old grouping with `ungroup()`


```

the discussion in https://github.com/tidyverse/dplyr/issues/1341 does not really help me.

**Comment by ChrisBeeley** [comment]
Sorry about this. It's not playing nicely with dplyr >0.8

Fixed in https://github.com/ChrisBeeley/gapminder/commit/a798afb3ef9c5122031073731327c4d859208c92

Please download again and let me know if you have any problems with it.

**Comment by Inkimar** [comment]
Thank you Chris, will try that out today!
